apiVersion: v1
kind: ServiceAccount
metadata:
  name: tequity-workload
  namespace: tequity
  annotations:
    # For Workload Identity
    iam.gke.io/gcp-service-account: tequity-workload@tequity-ajit.iam.gserviceaccount.com
