apiVersion: v1
kind: ServiceAccount
metadata:
  name: tequity-workload
  namespace: tequity
  annotations:
    # For Workload Identity - replace with your GCP project ID
    iam.gke.io/gcp-service-account: tequity-workload@PROJECT_ID.iam.gserviceaccount.com
